Repository bjanik/Discord_bot, pull requests merged in 2021-03, with the labels that each got.

#2 Update README.md
  README.md
Labels: documentation

#20 Container
  Dockerfile
  package-lock.json
  package.json
  run.sh
  tests/test.ts
  tsconfig.json
Labels: enhancement

#22 Container
  .github/workflows/main.yml
Labels: help wanted

#26 Using string-function mapping instead of ifs
  src/Bot.ts
Labels: enhancement

#29 Base unit tests config.
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
  run.sh
  tests/ping.test.ts
  tsconfig.json
Labels: testing

#31 CI Pipeline is working!
  .github/workflows/main.yml
  Dockerfile
  tsconfig.json
Labels: THE FIX 😎

#21 Roulette feature
  src/Bot.ts
  src/commands/RouletteCommand.ts
  tests/roulette.test.ts
Labels: New command, enhancement

#25 add help function
  src/Bot.ts
  src/commands/HelpCommand.ts
Labels: New command, documentation

#34 new readme
  .gitignore
  README.md
Labels: documentation

#38 add 8ballCommand.ts & update Bot.ts
  src/Bot.ts
  src/commands/8BallCommand.ts
Labels: New command

#39 Improved tests for kaamelott and roulette command
  package-lock.json
  package.json
  src/commands/RouletteCommand.ts
  src/commands/kaamelottCommand.ts
  tests/kaamelott.test.ts
  tests/roulette.test.ts
Labels: testing
